### ISSUE TITLE
update to released context

### ISSUE THREAD

**Issue by satra** [ohbm/eCobidas#156]
@Remi-Gau - here is a line that is being used which should be updated to the release context:

https://github.com/Remi-Gau/COBIDAS_chckls/blob/master/conversion_scripts/protocol.py#L10

https://raw.githubusercontent.com/ReproNim/reproschema/1.0.0-rc1/contexts/generic

**Comment by satra** [comment]
also if you want to look at the .github workflow for publishing the data collection ui, the demo-protocol under repronim is up to date.

**Comment by Remi-Gau** [comment]
will try to patch those before the talk tonight.

:crossed_fingers:

**Comment by Remi-Gau** [comment]
OK so the cobidas and cobidas are now "running"
