### ISSUE TITLE
split MRI and MEEG big spreasheets into small subsections

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/eCobidas#199]
### goals
- identify overlap between MRI and MEEG spreadsheet and extract those as core / common
- create a new spreadsheet for each of the main section / activity of those spreadsheets: currently this "fragmentation" of the spreadsheet into activities was done by the python script. Breaking those at an earlier stage will make it easier to work with each individual spreadsheet.

### workflow
- to be done in the [splitiing_process](https://github.com/Remi-Gau/eCobidas/tree/splitiing_process) branch
- this work will be done on the CSVs on there repo, so no work should be done on those main spreadsheets on the G drive
- before the work starts the latest version of the google spreasheet will be pushed on the repo

### to do
- [x] freeze the MRI and MEEG spreadsheet on the G drin (@Remi-Gau )
- [x] put the latest version of the MRI and MEEG csv on the repo (@Remi-Gau 

### Naming format for the spreadsheet

```bash
SectionName-modality.csv

# example

Participants-commom.csv

Acquisition-commom.csv
Acquisition-mri.csv
Acquisition-eeg.csv
Acquisition-meg.csv
```

@CPernet I don't remember the details of the naming format you suggested

### To be discussed later

What level of "granularity" do we want to do the splitting at? 

Let's start with the biggest chunks: 
- [x] participant sample
- [x] experimental design
- [x] acquisition
- [x] preprocessing
- [x] analysis
- [x] results
- [x] data sharing

And then we'll take it from there.

**Comment by Remi-Gau** [comment]
@CPernet 

I have done the splitting of the MRI and MEG spreadsheets.

The spreadsheets that are mri or meeg specific start with the `mri-` or `meg-` suffix respectively.

I think that there might be some work to see if there is some overlap between modalities that can be factored out in some core spreadsheet.

**Comment by CPernet** [comment]
i couldn't locate the changes?? or is it on the google drive

**Comment by Remi-Gau** [comment]
I had to do a lot git branch juggling because of some old weird old branching pattern.

The things were committed here: https://github.com/Remi-Gau/eCobidas/commit/67ae208578c6b8e58b102644427f48da883b55fb

If you :
```
git pull upstream master
git pull upstream splitiing_process
```
You should be good to go.
