### ISSUE TITLE
If user changes mind about an earlier choice and there is branching, things go crazy.

### ISSUE THREAD

**Issue by asoskic** [ohbm/eCOBIDAS#242]
Example: _"How were the EEG electrodes placed?"_ is the first question in the Hardware section, with two options - `cap or net` and `single electrodes`. The first option has follow-up subquestions (that show up only if I pick cap or net), and the latter doesn't.

1) If I pick `cap or net` first, follow-up questions for cap show up, as they should. But, if I change my mind and pick `single electrodes` before I go through all of the follow-up questions and I get to the part where I am again answering questions that are visible in both "branches" i.e. not only refer to `cap or net` (e.g. right after picking `cap or net` or after answering the first follow-up question), I get stuck. The follow-up questions that refer to the cap have now rightly disappeared, but no other questions appear and I cannot progress further down the list. The only way to go forward is to press `Skip` in which case I get questions that refer to `cap or net` again (which I also get if I decide to skip the question alltogether from the start).

2) If I pick `single electrodes`, that doesn't have follow-up questions, first, and then change mind and go for `cap or net` instead, I get a different type of problem. Switching to `cap or net` makes all the follow-up questions that relate to `cap or net` appear at the same time (of course unanswered). I can add answers to each of them, but I am not sure this is ideal because then some questions might get missed.

**Comment by Remi-Gau** [comment]
> 2\. If I pick `single electrodes`, that doesn't have follow-up questions, first, and then change mind and go for `cap or net` instead, I get a different type of problem. Switching to `cap or net` makes all the follow-up questions that relate to `cap or net` appear at the same time (of course unanswered). I can add answers to each of them, but I am not sure this is ideal because then some questions might get missed.

this is the way the app function at the moment: not sure we can easily change it for now

**Comment by KatarinaKetrinStekic** [comment]
Similarly, when you choose the `none` option for the question _'Did you apply any of the following offline (digital) filters?'_ in Chrome, no further questions show up. However, there's no issue with this in Edge.

**Comment by kehankehan** [comment]
In Acquisition section I tried change my choice for a previous question, and click "skip", it didn't elicit a new follow-up question for the changing choice. Still the old follow-up question (Chrome).

**Comment by KatarinaKetrinStekic** [comment]
If you change your choice in the Channel section in any of the questions, the follow-up question just disappears, but the follow-up question related to the other choice doesn't appear. You can't skip to the next question if you change your choice. So, it basically forces you to stick to the first choice if you wish to continue to the next step. (Chrome)
