### ISSUE TITLE
Can we have an option to force values depending on other responses?

### ISSUE THREAD

**Issue by asoskic** [ohbm/eCobidas#243]
e.g. "min N trials should be forced to be lower than avg N and max N trials" or "N subjects included needs to be smaller or equal to number subjects selected"

**Comment by asoskic** [comment]
another example: epoch beginning should be a smaller number than its end, the same goes for the measurement time windows

**Comment by asoskic** [comment]
another example: Baseline period: end should be numerically bigger (more positive) than beginning

**Comment by Remi-Gau** [comment]
not possible at the moment but having some sort of input validation would be nice

**Comment by Remi-Gau** [comment]
Opened an issue about this: https://github.com/ReproNim/reproschema/issues/444
