### ISSUE TITLE
Create boilerplate text for methods section automatic generation.

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/eCobidas#56]
We want the web-app to automatically generate a method section.

We therefore need to have some template or boilerplate method section with empty placeholders to be filled in by the different options chosen by users when they fill the list.

This requires writing those boilerplate texts for each `activity` of the checklist.

- This might need identifying which set of items can be grouped together to be put in the same sentence in the methods section.

A possible simple boilerplate to create is the M/EEG equivalent used by the [ `report` module pyBIDS](https://github.com/bids-standard/pybids/tree/master/bids/reports) to describe the content of BIDS data set. pyBIDS is very MRI focused but this could be a simple addition to the COBIDAS project that could be reinjected into the pyBIDS package.

- [ ] M/EEG descriptor just like the `report` module in pyBIDS

**Comment by Remi-Gau** [comment]
@cassgvp I have made a pull request #70  with some of the boilerplate section out there that I know already exist (fMRIprep, pybids, bids-matlab). 

Maybe we can start working on those and once again start simple and cover things that will be beneficial to the most

I suspect it will be easier to break down each big section into mini-section to make our life easier (especially for preprocessing).

One thing that I am not sure about is how to intelligently use place holders to generate those boiler plate:  should we give them very explicit names for the moment?

e.g: "the images were realigned using `moco_degrees_of_freedom` degrees of freedom.`

**Comment by jsheunis** [comment]
Can I help with this? I'm quite excited about this functionality.

**Comment by Remi-Gau** [comment]
YES. The more the merrier.

One of my plan for the holidays is to make the whole repo more friendly, with better doc and to better describe the most pressing issues.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
