### ISSUE TITLE
OHBM abstract and zoom meeting

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/eCobidas#67]
Hey all.

1) I am thinking of sending an abstract for this work for the next OHBM. Do you think it is a good idea? I might need some people willing to have a look at it. I am planning to make a pretty inclusive list of authors (pretty much based on the current list of contributors) on that so let me know if you do not want to be on this.

2) I have been working a bit on the next upgrade for the app but we should definitely have a zoom meeting  on all of this. So here are some possible dates: https://doodle.com/poll/eqxsa9mizifinbhb

Let me know what you think

@fedeadolfi  @kwiebels @m-miedema @zsjoerds @TimVanMourik @JamesEBartlett @joyswe @angietep @cassgvp @eduardklap

**Comment by kwiebels** [comment]
I think this is a great idea. I'm keen to be involved and definitely happy to read anything before the deadline.
I'm also keen to be a bit more involved again, but unfortunately won't be able to join the zoom meeting (the times are all between 2am and 6am here in NZ).

**Comment by Remi-Gau** [comment]
Hey everyone

Here is a first version of the OHBM abstract

Feel free to edit and make comments or suggestions.

If you would like to be an author, please create a profile on the OHBM 2020 abstract submission site (https://ww4.aievolution.com/hbm2001/), and add your name in the document.
